function(add_subdirectory_recursively dir)
    set(absolute_dir "${CMAKE_CURRENT_SOURCE_DIR}/${dir}")

    if(EXISTS "${absolute_dir}/CMakeLists.txt")
        add_subdirectory(${absolute_dir})
        message(STATUS "Subdirectory added to the project: ${absolute_dir}")
    else()
        file(GLOB children_dirs RELATIVE ${absolute_dir} ${absolute_dir}/*)
        foreach(child ${children_dirs})
            if(IS_DIRECTORY ${absolute_dir}/${child})
                add_subdirectory_recursively(${dir}/${child})
            endif()
        endforeach()
    endif()
endfunction()
